"""Stable platform identity helpers."""

from __future__ import annotations

import re

from unidecode import unidecode


TEAM_ALIASES = {
    "premier-league": {
        "AFC Bournemouth": "Bournemouth",
        "Arsenal FC": "Arsenal",
        "Aston Villa FC": "Aston Villa",
        "Brentford FC": "Brentford",
        "Brighton & Hove Albion": "Brighton",
        "Brighton & Hove Albion FC": "Brighton",
        "Brighton and Hove Albion": "Brighton",
        "Chelsea FC": "Chelsea",
        # Current ESPN promotion names must share the explicit historical
        # football-data identities; this is not fuzzy token stripping.
        "Coventry City": "Coventry",
        "Coventry City FC": "Coventry",
        "Crystal Palace FC": "Crystal Palace",
        "Everton FC": "Everton",
        "Fulham FC": "Fulham",
        "Hull City": "Hull",
        "Hull City AFC": "Hull",
        "Ipswich Town": "Ipswich",
        "Ipswich Town FC": "Ipswich",
        "Leeds United": "Leeds",
        "Leeds United FC": "Leeds",
        "Liverpool FC": "Liverpool",
        "Manchester City": "Man City",
        "Manchester City FC": "Man City",
        "Manchester United": "Man United",
        "Manchester United FC": "Man United",
        "Newcastle United": "Newcastle",
        "Newcastle United FC": "Newcastle",
        "Nottingham Forest": "Nott'm Forest",
        "Nottingham Forest FC": "Nott'm Forest",
        "Sunderland AFC": "Sunderland",
        "Tottenham Hotspur": "Tottenham",
        "Tottenham Hotspur FC": "Tottenham",
    },
    "championship": {
        "Birmingham City FC": "Birmingham",
        "Blackburn Rovers FC": "Blackburn",
        "Bolton Wanderers FC": "Bolton",
        "Bristol City FC": "Bristol City",
        "Burnley FC": "Burnley",
        "Cardiff City FC": "Cardiff",
        "Charlton Athletic FC": "Charlton",
        "Derby County FC": "Derby",
        "Lincoln City FC": "Lincoln City",
        "Middlesbrough FC": "Middlesbrough",
        "Millwall FC": "Millwall",
        "Norwich City FC": "Norwich",
        "Portsmouth FC": "Portsmouth",
        "Preston North End FC": "Preston",
        "Queens Park Rangers FC": "QPR",
        "Sheffield United FC": "Sheffield United",
        "Southampton FC": "Southampton",
        "Stoke City FC": "Stoke",
        "Swansea City AFC": "Swansea",
        "Watford FC": "Watford",
        "West Bromwich Albion": "West Brom",
        "West Bromwich Albion FC": "West Brom",
        "West Ham United FC": "West Ham",
        "Wolverhampton Wanderers FC": "Wolves",
        "Wrexham AFC": "Wrexham",
    },
    "la-liga": {
        "Alavés": "Alaves",
        "Athletic Club": "Ath Bilbao",
        "Atlético Madrid": "Ath Madrid",
        # Understat's title drops the accent and uses the full club name;
        # keep it on the same explicit canonical identity as the ESPN feed.
        "Atletico Madrid": "Ath Madrid",
        "CA Osasuna": "Osasuna",
        "Celta Vigo": "Celta",
        "Club Atlético de Madrid": "Ath Madrid",
        "Deportivo": "La Coruna",
        "Deportivo Alavés": "Alaves",
        "Elche CF": "Elche",
        "Espanyol": "Espanol",
        "FC Barcelona": "Barcelona",
        "Getafe CF": "Getafe",
        "Levante UD": "Levante",
        "Málaga CF": "Malaga",
        "RC Celta de Vigo": "Celta",
        "RC Deportivo": "La Coruna",
        "RC Deportivo La Coruña": "La Coruna",
        "RCD Espanyol de Barcelona": "Espanol",
        "Rayo Vallecano": "Vallecano",
        "Rayo Vallecano de Madrid": "Vallecano",
        "Real Betis": "Betis",
        "Real Betis Balompié": "Betis",
        "Real Madrid CF": "Real Madrid",
        "Real Racing Club de Santander": "Racing Santander",
        "Real Sociedad": "Sociedad",
        "Real Sociedad de Fútbol": "Sociedad",
        "Sevilla FC": "Sevilla",
        "Valencia CF": "Valencia",
        "Villarreal CF": "Villarreal",
    },
    "bundesliga": {
        "1. FC Köln": "FC Koln",
        "1. FC Union Berlin": "Union Berlin",
        "1. FSV Mainz 05": "Mainz",
        "Bayer 04 Leverkusen": "Leverkusen",
        "Bayer Leverkusen": "Leverkusen",
        # Understat and ESPN use different display titles for these clubs.
        "Borussia M.Gladbach": "M'gladbach",
        "Borussia Dortmund": "Dortmund",
        "Borussia Mönchengladbach": "M'gladbach",
        "Eintracht Frankfurt": "Ein Frankfurt",
        "FC Augsburg": "Augsburg",
        "FC Bayern München": "Bayern Munich",
        "FC Cologne": "FC Koln",
        "FC Schalke 04": "Schalke 04",
        "Hamburg SV": "Hamburg",
        "Hamburger SV": "Hamburg",
        "Mainz 05": "Mainz",
        "RasenBallsport Leipzig": "RB Leipzig",
        "SC Paderborn 07": "Paderborn",
        "SC Freiburg": "Freiburg",
        "SV 07 Elversberg": "Elversberg",
        "SV Werder Bremen": "Werder Bremen",
        "TSG 1899 Hoffenheim": "Hoffenheim",
        "TSG Hoffenheim": "Hoffenheim",
        "VfB Stuttgart": "Stuttgart",
    },
    "serie-a": {
        "AC Milan": "Milan",
        "AC Monza": "Monza",
        "ACF Fiorentina": "Fiorentina",
        "AS Roma": "Roma",
        "Atalanta BC": "Atalanta",
        "Bologna FC 1909": "Bologna",
        "Cagliari Calcio": "Cagliari",
        "Como 1907": "Como",
        "FC Internazionale Milano": "Inter",
        "Frosinone Calcio": "Frosinone",
        "Genoa CFC": "Genoa",
        "Internazionale": "Inter",
        "Juventus FC": "Juventus",
        "Parma Calcio 1913": "Parma",
        "SS Lazio": "Lazio",
        "SSC Napoli": "Napoli",
        "Torino FC": "Torino",
        "US Lecce": "Lecce",
        "US Sassuolo Calcio": "Sassuolo",
        "Udinese Calcio": "Udinese",
        "Venezia FC": "Venezia",
    },
    "ligue-1": {
        "AJ Auxerre": "Auxerre",
        "AS Monaco": "Monaco",
        "AS Monaco FC": "Monaco",
        "Angers SCO": "Angers",
        "ES Troyes AC": "Troyes",
        "FC Lorient": "Lorient",
        "Le Havre AC": "Le Havre",
        "Le Mans FC": "Le Mans",
        "Lille OSC": "Lille",
        "OGC Nice": "Nice",
        "Olympique Lyonnais": "Lyon",
        "Olympique de Marseille": "Marseille",
        "Paris Saint-Germain FC": "Paris SG",
        "Paris Saint-Germain": "Paris SG",
        "Paris Saint Germain": "Paris SG",
        "RC Strasbourg Alsace": "Strasbourg",
        "Racing Club de Lens": "Lens",
        "Stade Brestois 29": "Brest",
        "Stade Rennais": "Rennes",
        "Stade Rennais FC 1901": "Rennes",
        "Toulouse FC": "Toulouse",
    },
    "csl": {
        "Henan": "Henan FC",
        "Shanghai Port": "Shanghai Port FC",
        "Shenzhen Xinpengcheng": "Shenzhen Peng City",
        "Zhejiang Professional FC": "Zhejiang Professional",
        "上海海港": "Shanghai Port FC",
        "上海申花": "Shanghai Shenhua",
        "云南玉昆": "Yunnan Yukun",
        "北京国安": "Beijing Guoan",
        "大连英博海发": "Dalian Yingbo",
        "天津津门虎": "Tianjin Jinmen Tiger",
        "山东泰山": "Shandong Taishan",
        "成都蓉城": "Chengdu Rongcheng",
        "武汉三镇": "Wuhan Three Towns",
        "河南俱乐部彩陶坊": "Henan FC",
        "浙江俱乐部绿城": "Zhejiang Professional",
        "深圳新鹏城": "Shenzhen Peng City",
        "辽宁铁人楠波湾": "Liaoning Tieren",
        "重庆铜梁龙": "Chongqing Tonglianglong",
        "青岛海牛": "Qingdao Hainiu",
        "青岛西海岸": "Qingdao West Coast",
    },
}


def canonical_team_name(league_id: str, name: str) -> str:
    return TEAM_ALIASES.get(league_id, {}).get(name, name)


def team_id(league_id: str, name: str) -> str:
    canonical_name = canonical_team_name(league_id, name)
    slug = re.sub(r"[^a-z0-9]+", "-", unidecode(canonical_name).lower()).strip("-")
    return f"{league_id}:{slug}"
