from __future__ import annotations

from league_platform.current import _official_join_name
from league_platform.identity import canonical_team_name


CURRENT_PROVIDER_ALIASES = {
    "premier-league": {
        "Arsenal FC": "Arsenal",
        "Aston Villa FC": "Aston Villa",
        "Brentford FC": "Brentford",
        "Brighton & Hove Albion FC": "Brighton",
        "Chelsea FC": "Chelsea",
        "Coventry City FC": "Coventry",
        "Crystal Palace FC": "Crystal Palace",
        "Everton FC": "Everton",
        "Fulham FC": "Fulham",
        "Hull City AFC": "Hull",
        "Ipswich Town FC": "Ipswich",
        "Leeds United FC": "Leeds",
        "Liverpool FC": "Liverpool",
        "Manchester City FC": "Man City",
        "Manchester United FC": "Man United",
        "Newcastle United FC": "Newcastle",
        "Nottingham Forest FC": "Nott'm Forest",
        "Sunderland AFC": "Sunderland",
        "Tottenham Hotspur FC": "Tottenham",
    },
    "championship": {
        "Birmingham City FC": "Birmingham",
        "Blackburn Rovers FC": "Blackburn",
        "Bolton Wanderers FC": "Bolton",
        "Bristol City FC": "Bristol City",
        "Burnley FC": "Burnley",
        "Cardiff City FC": "Cardiff",
        "Charlton Athletic FC": "Charlton",
        "Derby County FC": "Derby",
        "Lincoln City FC": "Lincoln City",
        "Middlesbrough FC": "Middlesbrough",
        "Millwall FC": "Millwall",
        "Norwich City FC": "Norwich",
        "Portsmouth FC": "Portsmouth",
        "Preston North End FC": "Preston",
        "Queens Park Rangers FC": "QPR",
        "Sheffield United FC": "Sheffield United",
        "Southampton FC": "Southampton",
        "Stoke City FC": "Stoke",
        "Swansea City AFC": "Swansea",
        "Watford FC": "Watford",
        "West Bromwich Albion FC": "West Brom",
        "West Ham United FC": "West Ham",
        "Wolverhampton Wanderers FC": "Wolves",
        "Wrexham AFC": "Wrexham",
    },
    "la-liga": {
        "CA Osasuna": "Osasuna",
        "Club Atlético de Madrid": "Ath Madrid",
        "Deportivo Alavés": "Alaves",
        "Elche CF": "Elche",
        "FC Barcelona": "Barcelona",
        "Getafe CF": "Getafe",
        "Levante UD": "Levante",
        "Málaga CF": "Malaga",
        "RC Celta de Vigo": "Celta",
        "RC Deportivo La Coruña": "La Coruna",
        "RCD Espanyol de Barcelona": "Espanol",
        "Rayo Vallecano de Madrid": "Vallecano",
        "Real Betis Balompié": "Betis",
        "Real Madrid CF": "Real Madrid",
        "Real Racing Club de Santander": "Racing Santander",
        "Real Sociedad de Fútbol": "Sociedad",
        "Sevilla FC": "Sevilla",
        "Valencia CF": "Valencia",
        "Villarreal CF": "Villarreal",
    },
    "bundesliga": {
        "1. FC Köln": "FC Koln",
        "1. FSV Mainz 05": "Mainz",
        "Bayer 04 Leverkusen": "Leverkusen",
        "FC Bayern München": "Bayern Munich",
        "FC Schalke 04": "Schalke 04",
        "SV 07 Elversberg": "Elversberg",
        "SV Werder Bremen": "Werder Bremen",
        "TSG 1899 Hoffenheim": "Hoffenheim",
    },
    "serie-a": {
        "AC Monza": "Monza",
        "ACF Fiorentina": "Fiorentina",
        "Atalanta BC": "Atalanta",
        "Bologna FC 1909": "Bologna",
        "Cagliari Calcio": "Cagliari",
        "Como 1907": "Como",
        "FC Internazionale Milano": "Inter",
        "Frosinone Calcio": "Frosinone",
        "Genoa CFC": "Genoa",
        "Juventus FC": "Juventus",
        "SS Lazio": "Lazio",
        "SSC Napoli": "Napoli",
        "Torino FC": "Torino",
        "US Lecce": "Lecce",
        "US Sassuolo Calcio": "Sassuolo",
        "Udinese Calcio": "Udinese",
        "Venezia FC": "Venezia",
    },
    "ligue-1": {
        "AS Monaco FC": "Monaco",
        "Angers SCO": "Angers",
        "ES Troyes AC": "Troyes",
        "FC Lorient": "Lorient",
        "Le Mans FC": "Le Mans",
        "Lille OSC": "Lille",
        "OGC Nice": "Nice",
        "Olympique Lyonnais": "Lyon",
        "Olympique de Marseille": "Marseille",
        "Paris Saint-Germain FC": "Paris SG",
        "RC Strasbourg Alsace": "Strasbourg",
        "Racing Club de Lens": "Lens",
        "Stade Brestois 29": "Brest",
        "Stade Rennais FC 1901": "Rennes",
        "Toulouse FC": "Toulouse",
    },
    "csl": {
        "上海海港": "Shanghai Port FC",
        "上海申花": "Shanghai Shenhua",
        "云南玉昆": "Yunnan Yukun",
        "北京国安": "Beijing Guoan",
        "大连英博海发": "Dalian Yingbo",
        "天津津门虎": "Tianjin Jinmen Tiger",
        "山东泰山": "Shandong Taishan",
        "成都蓉城": "Chengdu Rongcheng",
        "武汉三镇": "Wuhan Three Towns",
        "河南俱乐部彩陶坊": "Henan FC",
        "浙江俱乐部绿城": "Zhejiang Professional",
        "深圳新鹏城": "Shenzhen Peng City",
        "辽宁铁人楠波湾": "Liaoning Tieren",
        "重庆铜梁龙": "Chongqing Tonglianglong",
        "青岛海牛": "Qingdao Hainiu",
        "青岛西海岸": "Qingdao West Coast",
    },
}


def test_current_provider_team_names_have_explicit_canonical_identities() -> None:
    for competition_id, aliases in CURRENT_PROVIDER_ALIASES.items():
        for provider_name, expected in aliases.items():
            assert canonical_team_name(competition_id, provider_name) == expected


def test_official_fixture_join_uses_the_same_canonical_identity_contract() -> None:
    pairs = (
        ("premier-league", "Fulham FC", "Fulham"),
        ("la-liga", "RC Deportivo La Coruña", "RC Deportivo"),
        ("serie-a", "Bologna FC 1909", "Bologna"),
        ("serie-a", "SS Lazio", "Lazio"),
    )
    for competition_id, current_name, official_name in pairs:
        assert _official_join_name(
            competition_id, current_name
        ) == _official_join_name(competition_id, official_name)
